{{- $root := . -}}

{{- range .Values.buckets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
type: Opaque
data:
  project: {{ .project | b64enc }}
  bucketname: {{ .bucketname | b64enc }}
  key: {{ .value | b64enc }}
---
{{- end }}
