apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: '{{ required "Set target.name" .Values.target.name }}-restarter'
  labels:
    app: '{{ .Values.target.name }}'
    release: '{{ .Release.Name }}'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    heritage: '{{ .Release.Service }}'

spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: '{{ .Values.target.name }}-restarter'
          labels:
            app: '{{ .Values.target.name }}-restarter'
            release: '{{ .Release.Name }}'

        spec:
          restartPolicy: Never
          serviceAccountName: '{{ .Values.target.name }}-restarter'
          containers:
            - name: '{{ .Values.target.name }}-restarter'
              image: bitnami/kubectl:1.15.3
              command:
                - rollout
                - restart
                - -n
                - '{{ .Release.Namespace }}'
                - '{{ .Values.target.type }}/{{ .Values.target.name }}'
