global:
  tenant:
    id: # required (e.g., c00001)
    name: # required (e.g, harald)

name: # required (e.g., axoom-myapp)

image:
  registry: # required (e.g. gcr.io)
  repository: # required (e.g., axoom-image/myteam/myservice)
  tag: # required (e.g., 1.0.0)
  pullPolicy: IfNotPresent

env: {}

labels: {}

resources:
  requests:
    memory: 64M
  limits:
    memory: 128M

replicas: 1

autoscaling:
  enabled: false
  maxReplicas: 3
  targetCpu: 50

rollingUpdate: true

nodeSelector: {}

persistence:
  enabled: false
  storageClass:
  size: 1G
  mountPath: # required if enabled

secrets: []

ingress:
  enabled: false
  istio:
    enabled: false
    gateway: istio-system/public
    timeout:
    retries: {}
  port: 80
  class: traefik-public
  domain: # required if enabled, except for class "cluster"
  additionalDomains: []
  annotations: {} # additional annotations besides ingress class
  tls: [] # ingress tls configuration

# livenessProbe:
#   initialDelaySeconds: 10 # Allow for long startup
#   httpGet:
#     port: http-ingress
#     path: /

# readinessProbe:
#   initialDelaySeconds: 2 # Accept traffic quickly
#   httpGet:
#     port: http-ingress
#     path: /

monitoring:
  enabled: true
  port: 5000

alerting:
  enabled: false
  labels: {}
  memoryUsage:
    thresholdFactor: 0.9
  http4xxRatio:
    sampleInterval: 5m
    referenceInterval: 1d
    thresholdFactor: 1.5
  responseTime:
    sampleInterval: 1h
    referenceInterval: 1d
    thresholdFactor: 1.5

sidecars: []

rbac:
  roles: []
  clusterRoles: []
