apiVersion: v1
name: docker-secrets
description: Logs in to AXOOM Docker Registries and optionally deploys secrets for GCS backups
sources:
  - https://tfs.inside-axoom.org/tfs/axoom/axoom/_git/Axoom.Platform.BaseAssets
