releases:
  - name: '{{ requiredEnv "TENANT_ID" }}-docker-secrets'
    namespace: '{{ requiredEnv "TENANT_ID" }}'
    chart: ./

    values:
      - global:
          tenant:
            id: '{{ requiredEnv "TENANT_ID" }}'

        registries:
          - domain: 'docker.axoom.cloud'
            username: 'axoom'
            password: {{ requiredEnv "DOCKER_REGISTRY_PASSWORD" | quote }}
          - domain: 'docker-ci.axoom.cloud'
            username: 'axoom'
            password: {{ requiredEnv "DOCKER_REGISTRY_PASSWORD" | quote }}

        opaques:
          {{- if env "GCS_BACKUP_KEYFILE" }}
          - name: gcs-backup-account
            value: {{ env "GCS_BACKUP_KEYFILE" | quote }}
          {{- end }}
