{{- if gt .Values.replicas 0.0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{ template "axoom.default-labels" . }}

spec:
  replicas: {{ .Values.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.name }}
      release: {{ .Release.Name }}

  {{- if .Values.persistence.enabled }}
  # Containers with volumes cannot perform rolling updates
  strategy:
    rollingUpdate:
      maxSurge: 0
  {{- end }}

  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name }}
        tenantId: '{{ .Values.global.tenant.id }}'
        tenantDomain: '{{ .Values.global.tenant.domain }}'

    spec:
      {{- if or .Values.rbac.roles .Values.rbac.clusterRoles }}
      serviceAccountName: {{ .Values.name }}
      {{- end }}

      {{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
      {{- end }}

      volumes:
        {{- if or .Values.persistence.enabled }}
        - name: persistence
          persistentVolumeClaim:
            claimName: {{ .Values.name }}
        {{- end }}
        {{- if or .Values.secrets.enabled }}
        - name: secrets
          secret:
            secretName: {{ .Values.name }}
        {{- end }}

      {{- if .Values.image.authenticated }}
      imagePullSecrets:
        - name: '{{ .Values.image.registry }}'
      {{- end }}
      dnsPolicy: {{ .Values.dns.policy }}
      {{- if .Values.dns.config }}
      dnsConfig:
{{ toYaml .Values.dns.config | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}

          image: '{{ .Values.image.registry }}/{{ required "Set image.repository" .Values.image.repository }}:{{ required "Set image.tag" .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: persistence
              mountPath: {{ required "Set persistence.mountPath" .Values.persistence.mountPath }}
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - name: secrets
              mountPath: {{ required "Set secrets.mountPath" .Values.secrets.mountPath }}
            {{- end }}

          ports:
            {{- if .Values.ingress.enabled }}
            - name: ingress
              containerPort: {{ .Values.ingress.port }}
            {{- end }}

            {{- if .Values.monitoring.enabled }}
            - name: monitoring
              containerPort: {{ .Values.monitoring.port }}
            {{- end }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}

          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}

          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
            {{- end }}
{{- end }}
