{{- if gt .Values.replicas 0 }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{ template "axoom.default-labels" . }}

spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      release: {{ .Release.Name }}

  {{- if .Values.persistence.enabled }}
  # Containers with volumes cannot perform rolling updates
  strategy:
    rollingUpdate:
      maxSurge: 0
  {{- end }}

  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name }}

    spec:
      replicas: {{ .Values.replicas }}
      serviceAccountName: {{ .Values.serviceAccountName | default "default" }}

      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}
      {{- end }}

      {{- if .Values.image.authenticated }}
      imagePullSecrets:
        - name: '{{ .Values.image.registry }}'
      {{- end }}

      containers:
        - name: {{ .Values.name }}

          image: '{{ .Values.image.registry }}/{{ required "Set image.repository" .Values.image.repository }}:{{ required "Set image.tag" .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ required "Set persistence.mountPath" .Values.persistence.mountPath }}
          {{- end }}

          ports:
            {{- if .Values.ingress.enabled }}
            - name: ingress
              containerPort: {{ .Values.ingress.port }}
            {{- end }}

            {{- if .Values.monitoring.enabled }}
            - name: monitoring
              containerPort: {{ .Values.monitoring.port }}
            {{- end }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}

          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}

          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
            {{- end }}
{{- end }}
