{{- if gt .Values.replicas 0.0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "axoom.default-labels" . | indent 4 }}

spec:
  replicas: {{ .Values.replicas }}

  selector:
    matchLabels:
{{ include "axoom.selector-labels" . | indent 6 }}

  strategy:
    {{- if .Values.persistence.enabled }}
    # Containers with volumes usually cannot perform rolling updates
    type: {{ .Values.updateStrategy | default "Recreate" }}
    {{- else}}
    type: {{ .Values.updateStrategy | default "RollingUpdate" }}
    {{- end}}

  template:
    metadata:
      labels:
{{ include "axoom.default-labels" . | indent 8 }}

    spec:
      volumes:
        {{- if or .Values.persistence.enabled }}
        - name: persistence
          persistentVolumeClaim:
            claimName: {{ .Values.name }}
        {{- end }}
        {{- range .Values.secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
        {{- end }}
        {{- range .Values.providedSecrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
        {{- end }}

      {{- if .Values.image.authenticated }}
      imagePullSecrets:
        - name: '{{ .Values.image.registry }}'
      {{- end }}

      {{- if or .Values.rbac.roles .Values.rbac.clusterRoles }}
      serviceAccountName: {{ .Values.name }}
      {{- end }}

      dnsPolicy: {{ .Values.dns.policy }}
      {{- if .Values.dns.config }}

      dnsConfig:
{{ toYaml .Values.dns.config | indent 8 }}
      {{- end }}

      {{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
      {{- end }}

      containers:
        - name: {{ .Values.name }}
          image: '{{ required "Set image.registry" .Values.image.registry }}/{{ required "Set image.repository" .Values.image.repository }}:{{ required "Set image.tag" .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: persistence
              mountPath: {{ required "Set persistence.mountPath" .Values.persistence.mountPath }}
            {{- end }}
            {{- range .Values.secrets }}
            - name: {{ .name }}
              mountPath: {{ required "Set secrets.mountPath" .mountPath }}
            {{- end }}
            {{- range .Values.providedSecrets }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}

          ports:
            {{- if .Values.ingress.enabled }}
            - name: ingress
              containerPort: {{ .Values.ingress.port }}
            {{- end }}
            {{- if .Values.monitoring.enabled }}
            - name: monitoring
              containerPort: {{ .Values.monitoring.port }}
            {{- end }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}

          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}

          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
            {{- end }}
{{- end }}
