{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "axoom.default-labels" . | indent 4 }}

spec:
  storageClassName: '{{ .Values.persistence.storageClass }}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '{{ .Values.persistence.size }}'
{{- end }}
