{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{ template "axoom.default-labels" . }}
type: Opaque
data:
  {{- range $key, $val := .files }}
  {{ $key | quote }}: {{ $val }}
  {{- end }}
{{- end }}
