{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  labels:
    {{ template "axoom.default-labels" . }}

spec:
  endpoints:
    - port: monitoring
      interval: {{ .Values.monitoring.interval }}

  selector:
    matchLabels:
      app: {{ .Values.name }}
      release: {{ .Release.Name }}

{{- end }}
