{{- if or .Values.ingress.enabled .Values.monitoring.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "axoom.default-labels" . | indent 4 }}
    monitoring: {{ .Values.monitoring.class }}

spec:
  selector:
{{ include "axoom.selector-labels" . | indent 4 }}

  ports:
    {{- if .Values.ingress.enabled }}
    - name: ingress
      port: 80
      targetPort: ingress
    {{- end }}

    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      port: 5000
      targetPort: monitoring
    {{- end }}

{{- end }}
