{{- if .Values.networkPolicy.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "etcd.default-labels" . | indent 4 }}

spec:
  podSelector:
    matchLabels:
{{ include "etcd.selector-labels" . | indent 6 }}

  ingress:
    - from:
        {{- range .Values.networkPolicy.ingressFromApps }}
        - podSelector:
            matchLabels:
              app: {{ . | quote }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ . | quote }}
        {{- end }}

        # Allow nodes to communicate amongst each other
        - podSelector:
            matchLabels:
{{ include "etcd.selector-labels" . | indent 14 }}

{{- if or .Values.metrics.enabled }}
        # Allow access from monitoring system
        - namespaceSelector:
{{ toYaml .Values.metrics.namespaceSelector | indent 12 }}
{{- end }}

{{- end }}
