{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "etcd.default-labels" . | indent 4 }}

spec:
  podSelector:
    matchLabels:
{{ include "etcd.selector-labels" . | indent 6 }}

  ingress:
    - from:
        # Allow etcd nodes to communicate amongst each other
        - podSelector:
            matchLabels:
{{ include "etcd.selector-labels" . | indent 14 }}
{{- if or .Values.prometheus.enabled }}
    # Allow access from Prometheus for monitoring
    - from:
        - namespaceSelector:
{{ toYaml .Values.prometheus.namespaceSelector | indent 14 }}
{{- end }}
{{- end }}
