apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "etcd.default-labels" . | indent 4 }}
  annotations:
    # Allow etcd nodes to communicate amongst each other during init, before their healthchecks pass
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"

spec:
  clusterIP: None
  publishNotReadyAddresses: true

  selector:
{{ include "etcd.selector-labels" . | indent 4 }}

  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: peer
      port: 2380
      targetPort: peer
