apiVersion: v1
name: axoom-service
version: 0 # This is replaced with a GitVersion-generated version by TFS
description: runs a service (with monitoring, ingress, etc.)
sources:
  - https://tfs.inside-axoom.org/tfs/axoom/axoom/_git/Axoom.Platform.BaseAssets
