releases:
  - name: '{{ requiredEnv "TENANT_ID" }}-image-pull-secret'
    namespace: '{{ requiredEnv "TENANT_ID" }}'
    chart: ./
    values:
      - domain: {{ requiredEnv "REGISTRY_DOMAIN" | quote }}
        username: {{ requiredEnv "REGISTRY_USERNAME" | quote }}
        password: {{ requiredEnv "REGISTRY_PASSWORD" | quote }}
