{{- if and (and .Values.ingress.enabled .Values.ingress.domain) (not .Values.ingress.istio.enabled) }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "generic-service.default-labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}

spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.name }}
              servicePort: http-ingress
    {{- $root := . -}}
    {{- range .Values.ingress.additionalDomains }}
    - host: '{{ . }}'
      http:
        paths:
          - backend:
              serviceName: {{ $root.Values.name }}
              servicePort: http-ingress
    {{- end }}

{{- end }}
