{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "axoom.default-labels" . | indent 4 }}

spec:
  selector:
    matchLabels:
{{ include "axoom.selector-labels" . | indent 6 }}
  endpoints:
    - port: monitoring
  targetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/instance
    - axoom.com/customer
    - app
    - release
    - tenantId
{{- end }}
