{{- if or .Values.ingress.enabled .Values.monitoring.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "generic-service.default-labels" . | indent 4 }}

spec:
  selector:
{{ include "generic-service.selector-labels" . | indent 4 }}

  ports:
    {{- if .Values.ingress.enabled }}
    - name: http-ingress
      port: 80
      targetPort: http-ingress

    {{- if .Values.ingress.grpcPort }}
    - name: grpc-ingress
      port: 1337
      targetPort: grpc-ingress
    {{- end }}

    {{- end }}

    {{- if .Values.monitoring.enabled }}
    - name: monitoring
      port: 5000
      targetPort: monitoring
    {{- end }}

{{- end }}
